"use client";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "../store";
import "../scss/style.scss";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="/bootstrap/css/bootstrap.css"
          rel="stylesheet"
          type="text/css"
        />
        {/* Animate.css */}
        <link
          href="/animate.css/animate.css"
          rel="stylesheet"
          type="text/css"
        />
        {/* Font Awesome iconic font */}
        <link
          href="/fontawesome/css/fontawesome-all.css"
          rel="stylesheet"
          type="text/css"
        />
        {/* Magnific Popup */}
        <link
          href="/magnific-popup/magnific-popup.css"
          rel="stylesheet"
          type="text/css"
        />
        {/* Slick carousel */}
        <link
          href="/slick/slick.css"
          rel="stylesheet"
          type="text/css"
        />
        {/* Fonts */}
        <link
          href="https://fonts.googleapis.com/css?family=Oswald:300,400,500,700"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700"
          rel="stylesheet"
          type="text/css"
        />
        {/* Theme styles */}
        <link
          href="/css/dot-icons.css"
          rel="stylesheet"
          type="text/css"
        />
        <link href="/css/theme.css" rel="stylesheet" type="text/css" />
      </head>
      <body className={inter.className}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
